// Hand-maintained snapshot of the public schema defined by the current migrations.
// Regenerate this file with the Supabase CLI after the user applies those SQL files.
// Keep the boxes identifier input overrides: triggers generate them and grants deny writes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activity_logs: {
        Row: {
          action: Database['public']['Enums']['audit_action']
          actor_id: string | null
          box_id: string | null
          created_at: string
          entity_id: string
          entity_type: Database['public']['Enums']['audit_entity']
          id: string
          snapshot: Json
        }
        Insert: {
          action: Database['public']['Enums']['audit_action']
          actor_id?: string | null
          box_id?: string | null
          created_at?: string
          entity_id: string
          entity_type: Database['public']['Enums']['audit_entity']
          id?: string
          snapshot?: Json
        }
        Update: {
          action?: Database['public']['Enums']['audit_action']
          actor_id?: string | null
          box_id?: string | null
          created_at?: string
          entity_id?: string
          entity_type?: Database['public']['Enums']['audit_entity']
          id?: string
          snapshot?: Json
        }
        Relationships: [
          {
            foreignKeyName: 'activity_logs_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      boxes: {
        Row: {
          box_code: string
          category: string | null
          cover_mime_type: string | null
          cover_object_key: string | null
          cover_size_bytes: number | null
          created_at: string
          description: string | null
          id: string
          location: string | null
          name: string
          owner_id: string
          public_id: string
          space_id: string
          updated_at: string
          visibility: Database['public']['Enums']['box_visibility']
        }
        Insert: {
          // Generated by boxes_assign_identifiers; column grants deny client writes.
          box_code?: never
          category?: string | null
          cover_mime_type?: string | null
          cover_object_key?: string | null
          cover_size_bytes?: number | null
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          name: string
          owner_id: string
          // Generated by boxes_assign_identifiers; column grants deny client writes.
          public_id?: never
          space_id: string
          updated_at?: string
          visibility?: Database['public']['Enums']['box_visibility']
        }
        Update: {
          // Immutable identifier; its trigger and column grants deny client writes.
          box_code?: never
          category?: string | null
          cover_mime_type?: string | null
          cover_object_key?: string | null
          cover_size_bytes?: number | null
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          name?: string
          owner_id?: string
          // Immutable identifier; its trigger and column grants deny client writes.
          public_id?: never
          space_id?: string
          updated_at?: string
          visibility?: Database['public']['Enums']['box_visibility']
        }
        Relationships: [
          {
            foreignKeyName: 'boxes_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'spaces'
            referencedColumns: ['id']
          },
        ]
      }
      items: {
        Row: {
          box_id: string
          category: string | null
          created_at: string
          description: string | null
          id: string
          image_mime_type: string | null
          image_object_key: string | null
          image_size_bytes: number | null
          name: string
          quantity: number
          stored_quantity: number
          updated_at: string
        }
        Insert: {
          box_id: string
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_mime_type?: string | null
          image_object_key?: string | null
          image_size_bytes?: number | null
          name: string
          quantity?: number
          // Initialized from quantity by a trigger; movement RPCs own later changes.
          stored_quantity?: never
          updated_at?: string
        }
        Update: {
          // Item moves must use move_item so the history remains complete.
          box_id?: never
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_mime_type?: string | null
          image_object_key?: string | null
          image_size_bytes?: number | null
          name?: string
          quantity?: number
          // Derived from movement RPCs and total-quantity edits.
          stored_quantity?: never
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'items_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      item_movements: {
        Row: {
          action: Database['public']['Enums']['item_movement_action']
          actor_id: string | null
          created_at: string
          from_box_id: string | null
          handler_label: string | null
          id: string
          item_id: string
          note: string | null
          quantity: number
          to_box_id: string | null
        }
        Insert: {
          // Append-only history is written exclusively by movement RPCs.
          action?: never
          actor_id?: never
          created_at?: never
          from_box_id?: never
          handler_label?: never
          id?: never
          item_id?: never
          note?: never
          quantity?: never
          to_box_id?: never
        }
        Update: {
          // Movement history is immutable to browser clients.
          action?: never
          actor_id?: never
          created_at?: never
          from_box_id?: never
          handler_label?: never
          id?: never
          item_id?: never
          note?: never
          quantity?: never
          to_box_id?: never
        }
        Relationships: [
          {
            foreignKeyName: 'item_movements_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_from_box_id_fkey'
            columns: ['from_box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_to_box_id_fkey'
            columns: ['to_box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      media_cleanup_jobs: {
        Row: {
          attempts: number
          created_at: string
          id: string
          last_error: string | null
          next_attempt_at: string
          object_key: string
          request_id: number | null
          status: Database['public']['Enums']['cleanup_status']
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          id?: string
          last_error?: string | null
          next_attempt_at?: string
          object_key: string
          request_id?: number | null
          status?: Database['public']['Enums']['cleanup_status']
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          id?: string
          last_error?: string | null
          next_attempt_at?: string
          object_key?: string
          request_id?: number | null
          status?: Database['public']['Enums']['cleanup_status']
          updated_at?: string
        }
        Relationships: []
      }
      media_uploads: {
        Row: {
          box_id: string
          confirmed_at: string | null
          created_at: string
          expires_at: string
          id: string
          item_id: string | null
          media_kind: Database['public']['Enums']['media_kind']
          mime_type: string
          object_key: string
          owner_id: string
          size_bytes: number
          status: Database['public']['Enums']['media_upload_status']
        }
        Insert: {
          box_id: string
          confirmed_at?: string | null
          created_at?: string
          expires_at: string
          id?: string
          item_id?: string | null
          media_kind: Database['public']['Enums']['media_kind']
          mime_type: string
          object_key: string
          owner_id: string
          size_bytes: number
          status?: Database['public']['Enums']['media_upload_status']
        }
        Update: {
          box_id?: string
          confirmed_at?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          item_id?: string | null
          media_kind?: Database['public']['Enums']['media_kind']
          mime_type?: string
          object_key?: string
          owner_id?: string
          size_bytes?: number
          status?: Database['public']['Enums']['media_upload_status']
        }
        Relationships: [
          {
            foreignKeyName: 'media_uploads_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'media_uploads_item_box_fkey'
            columns: ['item_id', 'box_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id', 'box_id']
          },
        ]
      }
      spaces: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          owner_id: string
          updated_at: string
          venue_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_id: string
          updated_at?: string
          venue_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
          venue_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'spaces_venue_id_fkey'
            columns: ['venue_id']
            isOneToOne: false
            referencedRelation: 'venues'
            referencedColumns: ['id']
          },
        ]
      }
      space_layouts: {
        Row: {
          created_at: string
          height_percent: number
          owner_id: string
          space_id: string
          updated_at: string
          width_percent: number
          x_percent: number
          y_percent: number
        }
        Insert: {
          created_at?: string
          height_percent: number
          owner_id: string
          space_id: string
          updated_at?: string
          width_percent: number
          x_percent: number
          y_percent: number
        }
        Update: {
          created_at?: string
          height_percent?: number
          owner_id?: string
          space_id?: string
          updated_at?: string
          width_percent?: number
          x_percent?: number
          y_percent?: number
        }
        Relationships: [
          {
            foreignKeyName: 'space_layouts_space_id_fkey'
            columns: ['space_id']
            isOneToOne: true
            referencedRelation: 'spaces'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          avatar_object_key: string | null
          created_at: string
          display_name: string | null
          id: string
          locale: string
          updated_at: string
        }
        Insert: {
          avatar_object_key?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          locale?: string
          updated_at?: string
        }
        Update: {
          avatar_object_key?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          locale?: string
          updated_at?: string
        }
        Relationships: []
      }
      venues: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_default: boolean
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          name: string
          owner_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      assign_box_identifiers: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      collect_media_cleanup_results: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      confirm_media_upload: {
        Args: { p_upload_id: string }
        Returns: undefined
      }
      create_media_download: {
        Args: { p_object_key: string }
        Returns: {
          download_url: string
          expires_at: string
        }[]
      }
      create_media_upload: {
        Args: {
          p_box_id: string
          p_item_id: string | null
          p_media_kind: Database['public']['Enums']['media_kind']
          p_mime_type: string
          p_size_bytes: number
        }
        Returns: {
          object_key: string
          upload_id: string
          upload_url: string
        }[]
      }
      create_profile_avatar_upload: {
        Args: { p_mime_type: string; p_size_bytes: number }
        Returns: { object_key: string; upload_id: string; upload_url: string }[]
      }
      confirm_profile_avatar_upload: {
        Args: { p_upload_id: string }
        Returns: undefined
      }
      create_profile_avatar_download: {
        Args: Record<PropertyKey, never>
        Returns: { download_url: string; expires_at: string }[]
      }
      update_profile_locale: {
        Args: { p_locale: string }
        Returns: undefined
      }
      enqueue_removed_media: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      expire_media_uploads: {
        Args: { p_cutoff?: string }
        Returns: number
      }
      get_public_box: {
        Args: { p_public_id: string }
        Returns: {
          box_code: string
          category: string | null
          cover_object_key: string | null
          description: string | null
          id: string
          items: Json
          location: string | null
          name: string
          owner_id: string
          public_id: string
          space_id: string
          space_name: string
          updated_at: string
          venue_name: string
          visibility: Database['public']['Enums']['box_visibility']
        }[]
      }
      move_item: {
        Args: { p_item_id: string; p_note?: string | null; p_target_box_id: string }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      prevent_box_identifier_update: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      process_media_cleanup_jobs: {
        Args: { p_batch_size?: number }
        Returns: number
      }
      return_item: {
        Args: { p_item_id: string; p_note?: string | null; p_quantity: number }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      search_my_items: {
        Args: { p_query: string }
        Returns: {
          box_id: string
          box_name: string
          box_public_id: string
          item_id: string
          item_name: string
          location: string | null
          quantity: number
          space_name: string
          venue_name: string
        }[]
      }
      set_updated_at: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      take_out_item: {
        Args: {
          p_handler_label?: string | null
          p_item_id: string
          p_note?: string | null
          p_quantity: number
        }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      write_activity_log: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
    }
    Enums: {
      audit_action: 'create' | 'update' | 'delete'
      audit_entity: 'space' | 'box' | 'item'
      box_visibility: 'public' | 'private'
      cleanup_status: 'pending' | 'processing' | 'completed' | 'failed'
      item_movement_action: 'take_out' | 'return' | 'move'
      media_kind: 'cover' | 'item'
      media_upload_status: 'pending' | 'confirmed' | 'expired'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
