// Hand-maintained snapshot of the public schema defined by the current migrations.
// Regenerate this file with the Supabase CLI after the user applies those SQL files.
// Keep the boxes identifier input overrides: triggers generate them and grants deny writes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activity_logs: {
        Row: {
          action: Database['public']['Enums']['audit_action']
          actor_id: string | null
          box_id: string | null
          created_at: string
          entity_id: string
          entity_type: Database['public']['Enums']['audit_entity']
          id: string
          snapshot: Json
        }
        Insert: {
          action: Database['public']['Enums']['audit_action']
          actor_id?: string | null
          box_id?: string | null
          created_at?: string
          entity_id: string
          entity_type: Database['public']['Enums']['audit_entity']
          id?: string
          snapshot?: Json
        }
        Update: {
          action?: Database['public']['Enums']['audit_action']
          actor_id?: string | null
          box_id?: string | null
          created_at?: string
          entity_id?: string
          entity_type?: Database['public']['Enums']['audit_entity']
          id?: string
          snapshot?: Json
        }
        Relationships: [
          {
            foreignKeyName: 'activity_logs_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      boxes: {
        Row: {
          box_code: string
          category: string | null
          cover_mime_type: string | null
          cover_object_key: string | null
          cover_size_bytes: number | null
          created_at: string
          description: string | null
          id: string
          location: string | null
          name: string
          owner_id: string
          public_id: string
          space_id: string
          updated_at: string
          visibility: Database['public']['Enums']['box_visibility']
        }
        Insert: {
          // Generated by boxes_assign_identifiers; column grants deny client writes.
          box_code?: never
          category?: string | null
          cover_mime_type?: string | null
          cover_object_key?: string | null
          cover_size_bytes?: number | null
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          name: string
          owner_id: string
          // Generated by boxes_assign_identifiers; column grants deny client writes.
          public_id?: never
          space_id: string
          updated_at?: string
          visibility?: Database['public']['Enums']['box_visibility']
        }
        Update: {
          // Immutable identifier; its trigger and column grants deny client writes.
          box_code?: never
          category?: string | null
          cover_mime_type?: string | null
          cover_object_key?: string | null
          cover_size_bytes?: number | null
          created_at?: string
          description?: string | null
          id?: string
          location?: string | null
          name?: string
          owner_id?: string
          // Immutable identifier; its trigger and column grants deny client writes.
          public_id?: never
          space_id?: string
          updated_at?: string
          visibility?: Database['public']['Enums']['box_visibility']
        }
        Relationships: [
          {
            foreignKeyName: 'boxes_space_id_fkey'
            columns: ['space_id']
            isOneToOne: false
            referencedRelation: 'spaces'
            referencedColumns: ['id']
          },
        ]
      }
      items: {
        Row: {
          box_id: string
          category: string | null
          created_at: string
          description: string | null
          id: string
          image_mime_type: string | null
          image_object_key: string | null
          image_size_bytes: number | null
          name: string
          quantity: number
          stored_quantity: number
          updated_at: string
        }
        Insert: {
          box_id: string
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_mime_type?: string | null
          image_object_key?: string | null
          image_size_bytes?: number | null
          name: string
          quantity?: number
          // Initialized from quantity by a trigger; movement RPCs own later changes.
          stored_quantity?: never
          updated_at?: string
        }
        Update: {
          // Item moves must use move_item so the history remains complete.
          box_id?: never
          category?: string | null
          created_at?: string
          description?: string | null
          id?: string
          image_mime_type?: string | null
          image_object_key?: string | null
          image_size_bytes?: number | null
          name?: string
          quantity?: number
          // Derived from movement RPCs and total-quantity edits.
          stored_quantity?: never
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'items_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      item_movements: {
        Row: {
          action: Database['public']['Enums']['item_movement_action']
          actor_id: string | null
          created_at: string
          from_box_id: string | null
          handler_label: string | null
          id: string
          item_id: string
          note: string | null
          quantity: number
          to_box_id: string | null
        }
        Insert: {
          // Append-only history is written exclusively by movement RPCs.
          action?: never
          actor_id?: never
          created_at?: never
          from_box_id?: never
          handler_label?: never
          id?: never
          item_id?: never
          note?: never
          quantity?: never
          to_box_id?: never
        }
        Update: {
          // Movement history is immutable to browser clients.
          action?: never
          actor_id?: never
          created_at?: never
          from_box_id?: never
          handler_label?: never
          id?: never
          item_id?: never
          note?: never
          quantity?: never
          to_box_id?: never
        }
        Relationships: [
          {
            foreignKeyName: 'item_movements_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'users'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_from_box_id_fkey'
            columns: ['from_box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_item_id_fkey'
            columns: ['item_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'item_movements_to_box_id_fkey'
            columns: ['to_box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
        ]
      }
      media_cleanup_jobs: {
        Row: {
          attempts: number
          created_at: string
          id: string
          last_error: string | null
          next_attempt_at: string
          object_key: string
          request_id: number | null
          status: Database['public']['Enums']['cleanup_status']
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          id?: string
          last_error?: string | null
          next_attempt_at?: string
          object_key: string
          request_id?: number | null
          status?: Database['public']['Enums']['cleanup_status']
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          id?: string
          last_error?: string | null
          next_attempt_at?: string
          object_key?: string
          request_id?: number | null
          status?: Database['public']['Enums']['cleanup_status']
          updated_at?: string
        }
        Relationships: []
      }
      media_uploads: {
        Row: {
          box_id: string
          confirmed_at: string | null
          created_at: string
          expires_at: string
          id: string
          item_id: string | null
          media_kind: Database['public']['Enums']['media_kind']
          mime_type: string
          object_key: string
          owner_id: string
          size_bytes: number
          status: Database['public']['Enums']['media_upload_status']
        }
        Insert: {
          box_id: string
          confirmed_at?: string | null
          created_at?: string
          expires_at: string
          id?: string
          item_id?: string | null
          media_kind: Database['public']['Enums']['media_kind']
          mime_type: string
          object_key: string
          owner_id: string
          size_bytes: number
          status?: Database['public']['Enums']['media_upload_status']
        }
        Update: {
          box_id?: string
          confirmed_at?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          item_id?: string | null
          media_kind?: Database['public']['Enums']['media_kind']
          mime_type?: string
          object_key?: string
          owner_id?: string
          size_bytes?: number
          status?: Database['public']['Enums']['media_upload_status']
        }
        Relationships: [
          {
            foreignKeyName: 'media_uploads_box_id_fkey'
            columns: ['box_id']
            isOneToOne: false
            referencedRelation: 'boxes'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'media_uploads_item_box_fkey'
            columns: ['item_id', 'box_id']
            isOneToOne: false
            referencedRelation: 'items'
            referencedColumns: ['id', 'box_id']
          },
        ]
      }
      packing_sessions: {
        Row: {
          box_id: string
          completed_at: string | null
          created_at: string
          current_revision: number
          id: string
          last_error_code: string | null
          model_id: string | null
          owner_id: string
          photo_count: number
          processed_at: string | null
          prompt_version: string | null
          schema_version: string | null
          started_at: string
          status: Database['public']['Enums']['packing_session_status']
          updated_at: string
        }
        Insert: {
          box_id: string
          completed_at?: string | null
          created_at?: string
          current_revision?: number
          id?: string
          last_error_code?: string | null
          model_id?: string | null
          owner_id: string
          photo_count?: number
          processed_at?: string | null
          prompt_version?: string | null
          schema_version?: string | null
          started_at?: string
          status?: Database['public']['Enums']['packing_session_status']
          updated_at?: string
        }
        Update: {
          [_ in never]: never
        }
        Relationships: []
      }
      packing_photos: {
        Row: {
          box_id: string
          confirmed_at: string | null
          created_at: string
          height: number | null
          id: string
          mime_type: string
          normalized_object_key: string | null
          object_key: string
          owner_id: string
          perceptual_hash: string | null
          quality_flags: Json
          sequence_no: number
          session_id: string
          sha256: string | null
          size_bytes: number
          updated_at: string
          upload_expires_at: string
          upload_status: Database['public']['Enums']['packing_photo_status']
          width: number | null
        }
        Insert: {
          [_ in never]: never
        }
        Update: {
          [_ in never]: never
        }
        Relationships: []
      }
      packing_atlases: {
        Row: {
          atlas_no: number
          created_at: string
          first_sequence_no: number
          height: number
          id: string
          confirmed_at: string | null
          last_sequence_no: number
          layout_version: string
          object_key: string
          session_id: string
          sha256: string
          size_bytes: number
          upload_status: string
          width: number
        }
        Insert: {
          [_ in never]: never
        }
        Update: {
          [_ in never]: never
        }
        Relationships: []
      }
      packing_detected_items: {
        Row: {
          analysis_revision: number
          box_id: string
          category: string | null
          cover_height: number | null
          cover_mime_type: string | null
          cover_object_key: string | null
          cover_size_bytes: number | null
          cover_width: number | null
          created_at: string
          crop_bbox: Json | null
          crop_source_photo_id: string | null
          crop_status: Database['public']['Enums']['packing_crop_status']
          crop_version: string | null
          description: string | null
          first_seen_photo_id: string | null
          id: string
          model_id: string
          name: string
          prompt_version: string
          published_at: string | null
          quantity_kind: Database['public']['Enums']['packing_quantity_kind']
          quantity_value: number | null
          representative_instance_id: string | null
          review_status: Database['public']['Enums']['packing_review_status']
          session_id: string
          updated_at: string
          visibility: Database['public']['Enums']['packing_visibility']
        }
        Insert: {
          [_ in never]: never
        }
        Update: {
          category?: string | null
          description?: string | null
          name?: string
          quantity_kind?: Database['public']['Enums']['packing_quantity_kind']
          quantity_value?: number | null
          review_status?: Database['public']['Enums']['packing_review_status']
        }
        Relationships: []
      }
      packing_item_promotions: {
        Row: {
          completed_at: string | null
          created_at: string
          detected_item_id: string
          id: string
          last_error_code: string | null
          owner_id: string
          session_id: string
          status: Database['public']['Enums']['packing_promotion_status']
          target_item_id: string
          target_object_key: string
          updated_at: string
        }
        Insert: {
          [_ in never]: never
        }
        Update: {
          [_ in never]: never
        }
        Relationships: []
      }
      spaces: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          owner_id: string
          updated_at: string
          venue_id: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          owner_id: string
          updated_at?: string
          venue_id: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
          venue_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'spaces_venue_id_fkey'
            columns: ['venue_id']
            isOneToOne: false
            referencedRelation: 'venues'
            referencedColumns: ['id']
          },
        ]
      }
      space_layouts: {
        Row: {
          created_at: string
          height_percent: number
          owner_id: string
          space_id: string
          updated_at: string
          width_percent: number
          x_percent: number
          y_percent: number
        }
        Insert: {
          created_at?: string
          height_percent: number
          owner_id: string
          space_id: string
          updated_at?: string
          width_percent: number
          x_percent: number
          y_percent: number
        }
        Update: {
          created_at?: string
          height_percent?: number
          owner_id?: string
          space_id?: string
          updated_at?: string
          width_percent?: number
          x_percent?: number
          y_percent?: number
        }
        Relationships: [
          {
            foreignKeyName: 'space_layouts_space_id_fkey'
            columns: ['space_id']
            isOneToOne: true
            referencedRelation: 'spaces'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          avatar_object_key: string | null
          created_at: string
          display_name: string | null
          id: string
          locale: string
          updated_at: string
        }
        Insert: {
          avatar_object_key?: string | null
          created_at?: string
          display_name?: string | null
          id: string
          locale?: string
          updated_at?: string
        }
        Update: {
          avatar_object_key?: string | null
          created_at?: string
          display_name?: string | null
          id?: string
          locale?: string
          updated_at?: string
        }
        Relationships: []
      }
      venues: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_default: boolean
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          name: string
          owner_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      assign_box_identifiers: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      collect_media_cleanup_results: {
        Args: Record<PropertyKey, never>
        Returns: number
      }
      confirm_media_upload: {
        Args: { p_upload_id: string }
        Returns: undefined
      }
      cancel_packing_session: {
        Args: { p_session_id: string }
        Returns: undefined
      }
      complete_packing_session: {
        Args: { p_session_id: string }
        Returns: Database['public']['Tables']['packing_sessions']['Row']
      }
      get_credit_summary: {
        Args: Record<PropertyKey, never>
        Returns: {
          credits_available: number
          credits_reserved: number
        }[]
      }
      list_credit_transactions: {
        Args: { p_limit?: number }
        Returns: {
          created_at: string
          credit_amount: number
          description: string | null
          id: string
          kind: Database['public']['Enums']['credit_transaction_kind']
        }[]
      }
      confirm_packing_photo_upload: {
        Args: { p_photo_id: string }
        Returns: undefined
      }
      confirm_packing_atlas_upload: {
        Args: { p_atlas_id: string }
        Returns: undefined
      }
      create_packing_media_download: {
        Args: { p_object_key: string }
        Returns: { download_url: string; expires_at: string }[]
      }
      create_packing_photo_upload: {
        Args: { p_mime_type: string; p_sequence_no: number; p_session_id: string; p_size_bytes: number }
        Returns: { object_key: string; photo_id: string; upload_url: string }[]
      }
      create_packing_atlas_upload: {
        Args: {
          p_atlas_no: number
          p_first_sequence_no: number
          p_height: number
          p_last_sequence_no: number
          p_session_id: string
          p_sha256: string
          p_size_bytes: number
          p_width: number
        }
        Returns: { atlas_id: string; object_key: string; upload_url: string }[]
      }
      create_packing_session: {
        Args: { p_box_id: string }
        Returns: Database['public']['Tables']['packing_sessions']['Row']
      }
      delete_packing_session: {
        Args: { p_session_id: string }
        Returns: undefined
      }
      delete_packing_photo: {
        Args: { p_photo_id: string }
        Returns: undefined
      }
      request_packing_item_promotion: {
        Args: { p_detected_item_id: string }
        Returns: Database['public']['Tables']['packing_item_promotions']['Row']
      }
      request_packing_reanalysis: {
        Args: { p_session_id: string }
        Returns: Database['public']['Tables']['packing_sessions']['Row']
      }
      update_packing_detected_item: {
        Args: {
          p_category: string | null
          p_description: string | null
          p_detected_item_id: string
          p_name: string
          p_quantity_kind: Database['public']['Enums']['packing_quantity_kind']
          p_quantity_value: number | null
          p_review_status: Database['public']['Enums']['packing_review_status']
        }
        Returns: Database['public']['Tables']['packing_detected_items']['Row']
      }
      merge_packing_detected_items: {
        Args: { p_source_item_id: string; p_target_item_id: string }
        Returns: Database['public']['Tables']['packing_detected_items']['Row']
      }
      create_media_download: {
        Args: { p_object_key: string }
        Returns: {
          download_url: string
          expires_at: string
        }[]
      }
      create_media_upload: {
        Args: {
          p_box_id: string
          p_item_id: string | null
          p_media_kind: Database['public']['Enums']['media_kind']
          p_mime_type: string
          p_size_bytes: number
        }
        Returns: {
          object_key: string
          upload_id: string
          upload_url: string
        }[]
      }
      create_profile_avatar_upload: {
        Args: { p_mime_type: string; p_size_bytes: number }
        Returns: { object_key: string; upload_id: string; upload_url: string }[]
      }
      confirm_profile_avatar_upload: {
        Args: { p_upload_id: string }
        Returns: undefined
      }
      create_profile_avatar_download: {
        Args: Record<PropertyKey, never>
        Returns: { download_url: string; expires_at: string }[]
      }
      update_profile_locale: {
        Args: { p_locale: string }
        Returns: undefined
      }
      enqueue_removed_media: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      expire_media_uploads: {
        Args: { p_cutoff?: string }
        Returns: number
      }
      get_public_box: {
        Args: { p_public_id: string }
        Returns: {
          box_code: string
          category: string | null
          cover_object_key: string | null
          description: string | null
          id: string
          items: Json
          location: string | null
          name: string
          owner_id: string
          public_id: string
          space_id: string
          space_name: string
          updated_at: string
          venue_name: string
          visibility: Database['public']['Enums']['box_visibility']
        }[]
      }
      move_item: {
        Args: { p_item_id: string; p_note?: string | null; p_target_box_id: string }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      prevent_box_identifier_update: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      process_media_cleanup_jobs: {
        Args: { p_batch_size?: number }
        Returns: number
      }
      return_item: {
        Args: { p_item_id: string; p_note?: string | null; p_quantity: number }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      search_my_items: {
        Args: { p_query: string }
        Returns: {
          box_id: string
          box_name: string
          box_public_id: string
          item_id: string
          item_name: string
          location: string | null
          quantity: number
          stored_quantity: number
          space_name: string
          venue_name: string
        }[]
      }
      search_my_inventory: {
        Args: { p_query: string }
        Returns: {
          box_id: string
          box_name: string
          box_public_id: string
          item_name: string
          location: string | null
          quantity: number | null
          quantity_kind: string
          result_id: string
          source: string
          space_name: string
          stored_quantity: number | null
          venue_name: string
        }[]
      }
      set_updated_at: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
      take_out_item: {
        Args: {
          p_handler_label?: string | null
          p_item_id: string
          p_note?: string | null
          p_quantity: number
        }
        Returns: {
          box_id: string
          item_id: string
          quantity: number
          stored_quantity: number
        }[]
      }
      write_activity_log: {
        Args: Record<PropertyKey, never>
        Returns: unknown
      }
    }
    Enums: {
      audit_action: 'create' | 'update' | 'delete'
      audit_entity: 'space' | 'box' | 'item'
      box_visibility: 'public' | 'private'
      cleanup_status: 'pending' | 'processing' | 'completed' | 'failed'
      credit_grant_kind: 'purchased' | 'promotional' | 'refund'
      credit_reservation_status: 'reserved' | 'consumed' | 'released'
      credit_transaction_kind: 'grant' | 'reserve' | 'consume' | 'release' | 'expire' | 'refund' | 'revoke'
      item_movement_action: 'take_out' | 'return' | 'move'
      media_kind: 'cover' | 'item'
      media_upload_status: 'pending' | 'confirmed' | 'expired'
      packing_crop_status: 'pending' | 'ready' | 'needs_review' | 'failed'
      packing_evidence_kind: 'first_seen' | 'supporting' | 'conflict' | 'verification'
      packing_job_stage: 'normalize' | 'atlas' | 'observe' | 'verify' | 'track_instances' | 'consolidate' | 'localize' | 'crop' | 'validate_crops' | 'publish'
      packing_job_status: 'pending' | 'processing' | 'completed' | 'failed'
      packing_photo_status: 'pending' | 'confirmed' | 'expired'
      packing_promotion_status: 'pending' | 'processing' | 'completed' | 'failed'
      packing_quantity_kind: 'exact' | 'at_least' | 'approximate' | 'unknown'
      packing_review_status: 'unreviewed' | 'needs_review' | 'confirmed' | 'corrected' | 'dismissed' | 'promoted'
      packing_session_status: 'capturing' | 'uploading' | 'queued' | 'processing' | 'ready' | 'partial_failed' | 'failed' | 'canceled'
      packing_tracking_status: 'provisional' | 'tracked' | 'ambiguous' | 'merged' | 'dismissed'
      packing_visibility: 'clear' | 'partial' | 'occluded' | 'reflective' | 'opaque_container' | 'unknown'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
