import type { Database } from './database.types'

type BoxInsert = Database['public']['Tables']['boxes']['Insert']
type BoxUpdate = Database['public']['Tables']['boxes']['Update']
type PublicBoxArgs = Database['public']['Functions']['get_public_box']['Args']
type CreatedBoxRpcArgs = Database['public']['Functions']['create_box']['Args']
type GrantAccountEntitlementRow = Database['public']['Functions']['grant_account_entitlement']['Returns'][number]
type VenueInsert = Database['public']['Tables']['venues']['Insert']
type VenueRow = Database['public']['Tables']['venues']['Row']
type SpaceInsert = Database['public']['Tables']['spaces']['Insert']
type AcceptInviteArgs = Database['public']['Functions']['accept_venue_invite']['Args']
type UpdateBoxArgs = Database['public']['Functions']['update_box']['Args']
type UpdateSpaceArgs = Database['public']['Functions']['update_space']['Args']
type PackingSessionRow = Database['public']['Tables']['packing_sessions']['Row']

const validBoxInsert = {
  name: '文具',
  owner_id: '00000000-0000-0000-0000-000000000001',
  space_id: '00000000-0000-0000-0000-000000000002',
} satisfies BoxInsert

const insertWithPublicId: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error public_id is generated by a database trigger.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const insertWithBoxCode: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error box_code is generated by a database trigger.
  box_code: 'BX-00001',
}

const validBoxUpdate = { name: '工具' } satisfies BoxUpdate
const validPublicBoxArgs = {
  p_public_id: '00000000-0000-0000-0000-000000000003',
} satisfies PublicBoxArgs
const validCreatedBoxRpcArgs = {
  p_space_id: '00000000-0000-0000-0000-000000000002',
  p_name: '文具',
  p_category: null,
  p_location: null,
  p_description: null,
  p_visibility: 'private',
} satisfies CreatedBoxRpcArgs
const tombstonedEntitlementGrant = {
  created: false,
  duplicate_active: false,
  entitlement_id: null,
} satisfies GrantAccountEntitlementRow
const createWithOwnerId: CreatedBoxRpcArgs = {
  ...validCreatedBoxRpcArgs,
  // @ts-expect-error create_box always derives owner_id from the authenticated caller.
  owner_id: '00000000-0000-0000-0000-000000000001',
}
const validVenueInsert = {
  name: '家里',
  owner_id: '00000000-0000-0000-0000-000000000001',
} satisfies VenueInsert
const validDefaultFlag: VenueRow['is_default'] = true
const validSpaceInsert = {
  name: '卧室',
  owner_id: '00000000-0000-0000-0000-000000000001',
  venue_id: '00000000-0000-0000-0000-000000000004',
} satisfies SpaceInsert
const validAcceptInvite: AcceptInviteArgs = { p_token: 'opaque-token' }
const validUpdateBox: UpdateBoxArgs = {
  p_box_id: '00000000-0000-0000-0000-000000000005',
  p_space_id: '00000000-0000-0000-0000-000000000002',
  p_name: '文具', p_category: null, p_location: null, p_description: null, p_visibility: 'private',
}
const validUpdateSpace: UpdateSpaceArgs = {
  p_space_id: '00000000-0000-0000-0000-000000000002',
  p_venue_id: '00000000-0000-0000-0000-000000000004',
  p_name: '卧室', p_description: null,
}
const validPackingSessionActor: PackingSessionRow['created_by'] = null
const validPackingSessionActorId: PackingSessionRow['created_by'] = '00000000-0000-0000-0000-000000000006'
// @ts-expect-error update_box derives ownership from the destination venue.
const forgedUpdateBoxOwner: UpdateBoxArgs = { ...validUpdateBox, p_owner_id: 'forged' }
// @ts-expect-error update_space uses p_venue_id only as the destination venue.
const forgedUpdateSpaceOwner: UpdateSpaceArgs = { ...validUpdateSpace, p_owner_id: 'forged' }
// @ts-expect-error actor identity comes from auth.uid(), never from the client
const forgedAcceptInvite: AcceptInviteArgs = { p_token: 'opaque-token', p_user_id: 'forged' }

const updateWithPublicId: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error public_id is immutable and not client-writable.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const updateWithBoxCode: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error box_code is immutable and not client-writable.
  box_code: 'BX-00002',
}

void insertWithPublicId
void insertWithBoxCode
void updateWithPublicId
void updateWithBoxCode
void validPublicBoxArgs
void validCreatedBoxRpcArgs
void tombstonedEntitlementGrant
void createWithOwnerId
void validVenueInsert
void validDefaultFlag
void validSpaceInsert
void validAcceptInvite
void validUpdateBox
void validUpdateSpace
void validPackingSessionActor
void validPackingSessionActorId
void forgedUpdateBoxOwner
void forgedUpdateSpaceOwner
void forgedAcceptInvite
