import type { Database } from './database.types'

type BoxInsert = Database['public']['Tables']['boxes']['Insert']
type BoxUpdate = Database['public']['Tables']['boxes']['Update']

const validBoxInsert = {
  name: '文具',
  owner_id: '00000000-0000-0000-0000-000000000001',
  space_id: '00000000-0000-0000-0000-000000000002',
} satisfies BoxInsert

const insertWithPublicId: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error public_id is generated by a database trigger.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const insertWithBoxCode: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error box_code is generated by a database trigger.
  box_code: 'BX-00001',
}

const validBoxUpdate = { name: '工具' } satisfies BoxUpdate

const updateWithPublicId: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error public_id is immutable and not client-writable.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const updateWithBoxCode: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error box_code is immutable and not client-writable.
  box_code: 'BX-00002',
}

void insertWithPublicId
void insertWithBoxCode
void updateWithPublicId
void updateWithBoxCode
