import type { Database } from './database.types'

type BoxInsert = Database['public']['Tables']['boxes']['Insert']
type BoxUpdate = Database['public']['Tables']['boxes']['Update']
type PublicBoxArgs = Database['public']['Functions']['get_public_box']['Args']
type CreatedBoxRpcArgs = Database['public']['Functions']['create_box']['Args']
type VenueInsert = Database['public']['Tables']['venues']['Insert']
type VenueRow = Database['public']['Tables']['venues']['Row']
type SpaceInsert = Database['public']['Tables']['spaces']['Insert']

const validBoxInsert = {
  name: '文具',
  owner_id: '00000000-0000-0000-0000-000000000001',
  space_id: '00000000-0000-0000-0000-000000000002',
} satisfies BoxInsert

const insertWithPublicId: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error public_id is generated by a database trigger.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const insertWithBoxCode: BoxInsert = {
  ...validBoxInsert,
  // @ts-expect-error box_code is generated by a database trigger.
  box_code: 'BX-00001',
}

const validBoxUpdate = { name: '工具' } satisfies BoxUpdate
const validPublicBoxArgs = {
  p_public_id: '00000000-0000-0000-0000-000000000003',
} satisfies PublicBoxArgs
const validCreatedBoxRpcArgs = {
  p_space_id: '00000000-0000-0000-0000-000000000002',
  p_name: '文具',
  p_category: null,
  p_location: null,
  p_description: null,
  p_visibility: 'private',
} satisfies CreatedBoxRpcArgs
const createWithOwnerId: CreatedBoxRpcArgs = {
  ...validCreatedBoxRpcArgs,
  // @ts-expect-error create_box always derives owner_id from the authenticated caller.
  owner_id: '00000000-0000-0000-0000-000000000001',
}
const validVenueInsert = {
  name: '家里',
  owner_id: '00000000-0000-0000-0000-000000000001',
} satisfies VenueInsert
const validDefaultFlag: VenueRow['is_default'] = true
const validSpaceInsert = {
  name: '卧室',
  owner_id: '00000000-0000-0000-0000-000000000001',
  venue_id: '00000000-0000-0000-0000-000000000004',
} satisfies SpaceInsert

const updateWithPublicId: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error public_id is immutable and not client-writable.
  public_id: '00000000-0000-0000-0000-000000000003',
}

const updateWithBoxCode: BoxUpdate = {
  ...validBoxUpdate,
  // @ts-expect-error box_code is immutable and not client-writable.
  box_code: 'BX-00002',
}

void insertWithPublicId
void insertWithBoxCode
void updateWithPublicId
void updateWithBoxCode
void validPublicBoxArgs
void validCreatedBoxRpcArgs
void createWithOwnerId
void validVenueInsert
void validDefaultFlag
void validSpaceInsert
